# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Account.API Build

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

permissions:
    id-token: write
    contents: read
    checks: write

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - name: Generate version
          id: version
          run: |
            VERSION="1.0.${{ github.run_number }}"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "Generated version: $VERSION"
        - name: Restore dependencies
          run: dotnet restore
          working-directory: src/
        - name: Build
          run: dotnet build --no-restore --configuration Release /p:Version=${{ env.VERSION }}
          working-directory: src/
        - name: Test
          run: dotnet test --verbosity normal --logger "trx"
          working-directory: src/        
        - name: Test Report
          uses: dorny/test-reporter@v1      
          if: always()
          with:
            name: Summary Tests
            path: "src/**/**/*.trx"
            reporter: dotnet-trx
            fail-on-error: true
        - name: Publish artifacts
          run: dotnet publish src/Account.Api.sln -c Release /p:Version=$VERSION
        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Account.Api-${{ env.VERSION }}
            path: ./artifacts/**/*
