# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Account.API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx"
      working-directory: src/    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: "**/*.trx"    
    - name: Display test results
      run: |
        echo "Displaying test results..."
        cat **/*.trx
